### ISSUE TITLE
Read block operation failed with error

### ISSUE THREAD

**Issue by YTLogos** [cc2qe/speedseq#141]
Hi, Thanks for developing the pipeline to detect the SV. I got some error when I run the speedseq sv pipeline
```
[E::bgzf_read] Read block operation failed with error 33 after 0 of 4 bytes
Traceback (most recent call last):
  File "/home/taoyan/miniconda3/envs/speedseq/speedseq//bin/svtyper", line 1806, in <module>
    sys.exit(main())
  File "/home/taoyan/miniconda3/envs/speedseq/speedseq//bin/svtyper", line 1801, in main
    args.max_reads)
  File "/home/taoyan/miniconda3/envs/speedseq/speedseq//bin/svtyper", line 1532, in sv_genotype
    read_batch, many = gather_reads(sample, chromB, posB, ciB, z, read_batch, max_reads)
  File "/home/taoyan/miniconda3/envs/speedseq/speedseq//bin/svtyper", line 1315, in gather_reads
    min(pos + ci[1] + fetch_flank, chrom_length))):
  File "pysam/libcalignmentfile.pyx", line 2094, in pysam.libcalignmentfile.IteratorRowRegion.__next__
IOError: truncated file
```

**Comment by YTLogos** [comment]
caused by the pysam version. After I downgraged to pysam version0.9.0, all is fine
